"""create studies

Revision ID: b7aa56d08f6d
Revises: a1c3e5f70911
Create Date: 2026-09-25 19:35:06.576243

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b7aa56d08f6d"
down_revision: str | Sequence[str] | None = "a1c3e5f70911"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "studies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("uploaded_by_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column(
            "file_names",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("n_images", sa.Integer(), nullable=False),
        sa.Column("status", sa.Enum("processing", "done", "failed", name="study_status"), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("quality_ok", sa.Boolean(), nullable=True),
        sa.Column("needs_review", sa.Boolean(), nullable=False),
        sa.Column("violation_codes", postgresql.ARRAY(sa.String(length=64)), nullable=False),
        sa.Column(
            "result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("model_version", sa.String(length=64), nullable=True),
        sa.Column("device_model", sa.String(length=255), nullable=True),
        sa.Column("processing_ms", sa.Integer(), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "review_status",
            sa.Enum("not_required", "pending", "confirmed", "corrected", name="review_status"),
            nullable=False,
        ),
        sa.Column("reviewed_by_id", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_quality_ok", sa.Boolean(), nullable=True),
        sa.Column("review_comment", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_studies_created_at"), "studies", ["created_at"], unique=False)
    op.create_index(op.f("ix_studies_review_status"), "studies", ["review_status"], unique=False)
    op.create_index(op.f("ix_studies_uploaded_by_id"), "studies", ["uploaded_by_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_studies_uploaded_by_id"), table_name="studies")
    op.drop_index(op.f("ix_studies_review_status"), table_name="studies")
    op.drop_index(op.f("ix_studies_created_at"), table_name="studies")
    op.drop_table("studies")
    # ### end Alembic commands ###
    # Enum-типы Postgres живут отдельно от таблицы — удаляем их после drop_table (урок 4)
    sa.Enum(name="review_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="study_status").drop(op.get_bind(), checkfirst=True)
